### ISSUE TITLE
NullReferenceException possibly related to SeedTotem@1.0.6

### ISSUE THREAD

**Issue by DiskImage** [MathiasDecrock/Valheim-SeedTotem#2]
I updated to the new 1.0.6 version to try the gathering skill with the totem harvest and noticed my totem vanished. And then I couldn't build a new one. I checked the log and saw this error immediately after the mod loads. I'm not sure they're related, but this was also the only update I had today. Can recreate with JUST SeedTotem installed from the Thunderstore

```
[Info   :   BepInEx] Loading [Seed Totem 1.0.6]
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'ModConfigEnforcer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
```

**Comment by DiskImage** [comment]
I think I see what my problem was, but now I have new ones. I went to see if I could fix this in the dl files and saw the README.md changed from master, which was what I was referencing, and added a warning:

`> :warning: Also requires Mod Config Enforcer, not available on Thunderstore, get it here: https://www.nexusmods.com/valheim/mods/460`

Change request: Add this warning to the manifest so it displays in the thunderstore description and isn't as easy to miss. IDK if we can get the MCE people to upload to thunderstore, too, to enable dependency downloading.

New problem:
I added that ModConfigEnforcer dll to my profile's plugins dir and re-ran the game on `SeedTotem@1.0.6`; I'm now unable to load the game after selecting a world. When I hit `Start` I go to a loading screen like normal, but the loading screen never ceases. Here's the new error in the log.
```
[Info   : Unity Log] ---- Registering custom prefabs ----
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
SeedTotemMod.SeedTotemPrefabConfig.Register () (at <c03a2561724146588ffe947b0abe289e>:0)
JotunnLib.Managers.PrefabManager.RegisterPrefab (JotunnLib.Entities.PrefabConfig prefabConfig) (at <769eb86548774a248304179a58ccb261>:0)
SeedTotemMod.SeedTotemMod.RegisterPrefabs (System.Object sender, System.EventArgs e) (at <c03a2561724146588ffe947b0abe289e>:0)
JotunnLib.Managers.PrefabManager.Load () (at <769eb86548774a248304179a58ccb261>:0)
JotunnLib.Patches.ZNetScenePatches+AwakePatch.Postfix () (at <769eb86548774a248304179a58ccb261>:0)
(wrapper dynamic-method) ZNetScene.DMD<ZNetScene::Awake>(ZNetScene)
```

**Comment by MathiasDecrock** [comment]
Sorry, I haven't been keeping this repository up to date, I've moved it into a new folder with my other mods. I'll push them once the full solution is uploaded.
There is a new version on NexusMods, that might resolve your issues, I'll have to get it on ThunderStore, but as you said, I don't have all dependencies there, so it feels a bit pointless to put it on there.

**Comment by DiskImage** [comment]
I installed 1.0.8 from NexusMods and it resolved the login issue. I'm also able to harvest slap while using the Gathering skill mod!
